### ISSUE TITLE
option for volume change with mousewheel

### ISSUE THREAD

**Issue by milkmiruku** [GeorgeFilipkin/pulsemixer#27]
Current mousewheel selects devices. It would be handy if that could be switched to change the device volume.

**Comment by GeorgeFilipkin** [comment]
Done. Wheel up to increase volume, wheel down to decrease, left mouse click to select a device. Can be reverted back to the old behavior with `--no-mouse` option.

**Comment by milkmiruku** [comment]
Thanks! Not full working for me though - mousewheel scroll up works, but scroll down doesn't. Also, the bottom side mouse button8 moves the volume up, the top side button does nothing.

**Comment by GeorgeFilipkin** [comment]
https://gist.github.com/GeorgeFilipkin/f24d4d1d174072ebe8cc9a78580ccfa6

@milkmiruku Try running this gist, `python3 ./mouse.py`, then press/scroll the buttons in questions - it should print some numbers. I need those numbers and the corresponding buttons.

**Comment by milkmiruku** [comment]
Mouse wheel up = 65536
Mouse wheel down = 2097152
Button 9 (top side) = 69206016
Button 8 (bottom side) = 67174400

**Comment by GeorgeFilipkin** [comment]
@milkmiruku Should work now. Try it.

**Comment by milkmiruku** [comment]
`/usr/bin/pulsemixer is owned by pulsemixer-git 1:88.fb9457f-1`

Still the same behaviour :/

**Comment by GeorgeFilipkin** [comment]
@milkmiruku  Alright, this is weird, but the only way I could get scroll down to work in Arch is to "bitwise and" it with A_BOLD, which is bold text.

But now it really should work.

**Comment by milkmiruku** [comment]
That works, thanks :)
